# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Window(object):
    def setupUi(self, Admin_Window):
        Admin_Window.setObjectName("Admin_Window")
        Admin_Window.resize(1028, 747)
        self.centralwidget = QtWidgets.QWidget(Admin_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(70, 40, 371, 451))
        self.frame1.setStyleSheet("#frame1{\n"
"background-color: qlineargradient(spread:pad, x1:0.920727, y1:0.881, x2:0.693, y2:0.795818, stop:0.107955 rgba(0, 0, 0, 255), stop:0.642045 rgba(255, 255, 255, 255));\n"
"border-radius:20px}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setGeometry(QtCore.QRect(70, 20, 141, 31))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"font: 75 12pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame1)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 50, 371, 161))
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(255,255,255,150);\n"
"    border:none;\n"
"    border-bottom:1px solid black\n"
"\n"
"}\n"
"QPushButton{\n"
"    bordeo-radius:8px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_search = QtWidgets.QPushButton(self.page_3)
        self.pushButton_search.setGeometry(QtCore.QRect(170, 110, 81, 31))
        self.pushButton_search.setObjectName("pushButton_search")
        self.lineEdit_search = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_search.setGeometry(QtCore.QRect(0, 80, 251, 31))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(140, 60, 211, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget_2.addWidget(self.page_3)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame1)
        self.pushButton_exit.setGeometry(QtCore.QRect(0, 400, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 10, 541, 511))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.341, y2:0.489, stop:0 rgba(0, 0, 0, 255), stop:0.375 rgba(255, 255, 255, 255));\n"
"border-radius:25px}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 541, 421))
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.966, y1:0.914773, x2:0.534091, y2:0.716, stop:0 rgba(0, 0, 0, 255), stop:0.323864 rgba(255, 255, 255, 255));}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(23, 6, 91, 31))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 30, 551, 291))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_111 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_111.setGeometry(QtCore.QRect(20, 380, 75, 23))
        self.pushButton_111.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_111.setObjectName("pushButton_111")
        self.pushButton_222 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_222.setGeometry(QtCore.QRect(110, 380, 75, 23))
        self.pushButton_222.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_222.setObjectName("pushButton_222")
        self.pushButton_black = QtWidgets.QPushButton(self.page_2)
        self.pushButton_black.setGeometry(QtCore.QRect(200, 380, 75, 23))
        self.pushButton_black.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_black.setObjectName("pushButton_black")
        self.pushButton_white = QtWidgets.QPushButton(self.page_2)
        self.pushButton_white.setGeometry(QtCore.QRect(280, 380, 75, 23))
        self.pushButton_white.setStyleSheet("QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_white.setObjectName("pushButton_white")
        self.lineEdit_object = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_object.setGeometry(QtCore.QRect(170, 330, 171, 21))
        self.lineEdit_object.setObjectName("lineEdit_object")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 320, 171, 31))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_2)
        Admin_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Admin_Window)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Admin_Window)

    def retranslateUi(self, Admin_Window):
        _translate = QtCore.QCoreApplication.translate
        Admin_Window.setWindowTitle(_translate("Admin_Window", "MainWindow"))
        self.label.setText(_translate("Admin_Window", "管理员界面"))
        self.pushButton_search.setText(_translate("Admin_Window", "查询"))
        self.label_3.setText(_translate("Admin_Window", "输入想要查询的人员"))
        self.label_6.setText(_translate("Admin_Window", "（用户/值班/安全设施）"))
        self.pushButton_exit.setText(_translate("Admin_Window", "退出"))
        self.label_4.setText(_translate("Admin_Window", "查询结果："))
        self.pushButton_111.setText(_translate("Admin_Window", "归还"))
        self.pushButton_222.setText(_translate("Admin_Window", "未归还"))
        self.pushButton_black.setText(_translate("Admin_Window", "关小黑屋"))
        self.pushButton_white.setText(_translate("Admin_Window", "移除小黑屋"))
        self.label_7.setText(_translate("Admin_Window", "输入用户id来进行以下操作："))
