# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tool_Window(object):
    def setupUi(self, Tool_Window):
        Tool_Window.setObjectName("Tool_Window")
        Tool_Window.resize(766, 600)
        self.centralwidget = QtWidgets.QWidget(Tool_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(40, 60, 251, 421))
        self.frame1.setStyleSheet("#frame1{\n"
"background-color: qlineargradient(spread:pad, x1:0.920727, y1:0.881, x2:0.693, y2:0.795818, stop:0.107955 rgba(0, 0, 0, 255), stop:0.642045 rgba(255, 255, 255, 255));\n"
"border-radius:20px}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setGeometry(QtCore.QRect(70, 20, 141, 31))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"font: 75 12pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 221, 31))
        self.label_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame1)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 170, 251, 191))
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(255,255,255,150);\n"
"    border:none;\n"
"    border-bottom:1px solid black\n"
"\n"
"}\n"
"QPushButton{\n"
"    bordeo-radius:8px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_Find = QtWidgets.QPushButton(self.page_3)
        self.pushButton_Find.setGeometry(QtCore.QRect(170, 110, 81, 31))
        self.pushButton_Find.setObjectName("pushButton_Find")
        self.lineEdit_Findtool = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_Findtool.setGeometry(QtCore.QRect(0, 80, 251, 31))
        self.lineEdit_Findtool.setObjectName("lineEdit_Findtool")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_exit = QtWidgets.QPushButton(self.page_3)
        self.pushButton_exit.setGeometry(QtCore.QRect(0, 170, 81, 21))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.stackedWidget_2.addWidget(self.page_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(290, 60, 451, 421))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.341, y2:0.489, stop:0 rgba(0, 0, 0, 255), stop:0.375 rgba(255, 255, 255, 255));\n"
"border-radius:25px}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.966, y1:0.914773, x2:0.534091, y2:0.716, stop:0 rgba(0, 0, 0, 255), stop:0.323864 rgba(255, 255, 255, 255));}\n"
"QLineEdit{\n"
"    background-color:rgba(255,255,255,150);\n"
"    border:none;\n"
"    border-bottom:1px solid black\n"
"\n"
"}\n"
"QPushButton{\n"
"    bordeo-radius:8px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textEdit = QtWidgets.QTextEdit(self.page)
        self.textEdit.setGeometry(QtCore.QRect(40, 30, 351, 131))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_back = QtWidgets.QPushButton(self.page)
        self.pushButton_back.setGeometry(QtCore.QRect(310, 240, 81, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(23, 6, 91, 31))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 30, 451, 271))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 300, 451, 81))
        self.stackedWidget_3.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(255,255,255,150);\n"
"    border:none;\n"
"    border-bottom:1px solid black\n"
"\n"
"}\n"
"QPushButton{\n"
"    bordeo-radius:8px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Update = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_Update.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.lineEdit_Update.setObjectName("lineEdit_Update")
        self.pushButton_next = QtWidgets.QPushButton(self.page_4)
        self.pushButton_next.setGeometry(QtCore.QRect(200, 30, 71, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.stackedWidget_3.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(23, 11, 141, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_number = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_number.setGeometry(QtCore.QRect(20, 39, 141, 31))
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.pushButton_Update_2 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_Update_2.setGeometry(QtCore.QRect(190, 50, 75, 23))
        self.pushButton_Update_2.setObjectName("pushButton_Update_2")
        self.stackedWidget_3.addWidget(self.page_5)
        self.stackedWidget.addWidget(self.page_2)
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_4.setGeometry(QtCore.QRect(0, 380, 451, 41))
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget_4.addWidget(self.page_6)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_9 = QtWidgets.QLabel(self.page_9)
        self.label_9.setGeometry(QtCore.QRect(70, 10, 291, 20))
        self.label_9.setObjectName("label_9")
        self.stackedWidget_4.addWidget(self.page_9)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_7 = QtWidgets.QLabel(self.page_7)
        self.label_7.setGeometry(QtCore.QRect(160, 10, 201, 21))
        self.label_7.setStyleSheet("font: 11pt \"宋体\";")
        self.label_7.setObjectName("label_7")
        self.stackedWidget_4.addWidget(self.page_7)
        Tool_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tool_Window)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Tool_Window)

    def retranslateUi(self, Tool_Window):
        _translate = QtCore.QCoreApplication.translate
        Tool_Window.setWindowTitle(_translate("Tool_Window", "MainWindow"))
        self.label.setText(_translate("Tool_Window", "器材预订界面"))
        self.label_2.setText(_translate("Tool_Window", "温馨提示：器材租借时间均按小时结账！"))
        self.pushButton_Find.setText(_translate("Tool_Window", "查询"))
        self.label_3.setText(_translate("Tool_Window", "输入想要查询的器材"))
        self.pushButton_exit.setText(_translate("Tool_Window", "退出"))
        self.pushButton_back.setText(_translate("Tool_Window", "返回"))
        self.label_4.setText(_translate("Tool_Window", "查询结果："))
        self.label_5.setText(_translate("Tool_Window", "输入你想预定的物品id："))
        self.pushButton_next.setText(_translate("Tool_Window", "确定"))
        self.label_6.setText(_translate("Tool_Window", "你想要多少个？"))
        self.pushButton_Update_2.setText(_translate("Tool_Window", "预定"))
        self.label_9.setText(_translate("Tool_Window", "输入物品id或输入数量值无效！请重试"))
        self.label_7.setText(_translate("Tool_Window", "库存数量不足！请重试"))
